export const reports =
{
    "data": [
        {
            "Id": "132706-f303",
            "Name": "Olympic Medals Map",
            "Extension": ".trdp",
            "Description": "Presents map layout of the Olympic medals by national teams and associations.",
            "CategoryId": "172426-4389",
            "CategoryName": "Drafts",
            "Revision": "6",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1631716029000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "183054-f4b3",
            "Name": "Invoice",
            "Extension": ".trdp",
            "Description": "Invoice report implemented using master-detail approach.",
            "CategoryId": "183053-1db9",
            "CategoryName": "Published",
            "Revision": "1",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1512556302000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "183054-aabd",
            "Name": "Employee Sales Summary",
            "Extension": ".trdp",
            "Description": "Displays sales statistics for an individual employee per month.",
            "CategoryId": "183053-1db9",
            "CategoryName": "Published",
            "Revision": "1",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1512556214000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "183054-32de",
            "Name": "Product Sales",
            "Extension": ".trdp",
            "Description": "Crosstab summary of AdventureWorks sales, grouped by product category over a 4 year period.",
            "CategoryId": "183053-1db9",
            "CategoryName": "Published",
            "Revision": "1",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1512556072000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "173244-6838",
            "Name": "Sales Summary",
            "Extension": ".trdp",
            "Description": "Display sales statistics per month.",
            "CategoryId": "172426-4389",
            "CategoryName": "Drafts",
            "Revision": "1",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1512555835000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "183053-d0c5",
            "Name": "Dashboard",
            "Extension": ".trdp",
            "Description": "Performance overview of the AdventureWorks Sales Department.",
            "CategoryId": "183053-1db9",
            "CategoryName": "Published",
            "Revision": "1",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1511449831000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "174009-a77c",
            "Name": "Cars In Stock",
            "Extension": ".trdp",
            "Description": "Lists performance cars in stock at Dealer Inc.",
            "CategoryId": "172426-4389",
            "CategoryName": "Drafts",
            "Revision": "0",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1511372409000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "173735-c748",
            "Name": "Barcode Demo",
            "Extension": ".trdp",
            "Description": "Displays various barcode types.",
            "CategoryId": "172426-4389",
            "CategoryName": "Drafts",
            "Revision": "0",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1511372255000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "183055-ab17",
            "Name": "Product Line Sales",
            "Extension": ".trdp",
            "Description": "Top 10 best performing sales people and stores.",
            "CategoryId": "183053-1db9",
            "CategoryName": "Published",
            "Revision": "0",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1509388255000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        },
        {
            "Id": "183055-9ff2",
            "Name": "Sales Order Details",
            "Extension": ".trdp",
            "Description": "Details subreport for the Invoice report.",
            "CategoryId": "183053-1db9",
            "CategoryName": "Published",
            "Revision": "0",
            "CreatedBy": "John Doe",
            "LockedBy": "Unlocked",
            "ModifiedBy": "John Doe",
            "DateModifiedUtc": "\/Date(1509388255000)\/",
            "Favorite": false,
            "CanModify": false,
            "CanDelete": false,
            "CanView": true,
            "CreatedByUserLink": "",
            "ModifiedByUserLink": "",
            "IsUserLinkVisible": false,
            "EnableWebReportDesigner": true
        }
    ],
    "Total": 10,
    "AggregateResults": null,
    "Errors": null
}
